# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Python CI/CD


#Workflow trigger
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]   
  
#Workflow build function
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip #installs pygame dependencies
        pip install pygame flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
        pip install --upgrade sentry-sdk

#Testing codes with pytest    
    - name: Test with pytest
      id: TestWithPytest
      run: |
           pytest -v --junitxml=report.xml
    - if: ${{failure()}}       
      name: Create Issues
      uses: nashmaniac/create-issue-action@v1.1
      with:
          title: Build Failed #Build Fail action
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: worflow-failed
          body: Workflow failed for commit ${{github.sha}} @ ${{github.ref}}

#Unit test results (create report.xml)
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.5
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: report.xml

#Docker: (Creates new issue to repository)
  assign:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: add-new-issues-to-repository-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/ETI-Oct2020-Team5/RatVenture/projects/1
        GITHUB_PROJECT_COLUMN_NAME: To do

    - name: Sentry Release
      # You may pin to the exact commit or the version.
      # uses: getsentry/action-release@641a80f3e05619b174bcacbfa3b69dff382d2a33
      uses: getsentry/action-release@v1.1.5
      env: 
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

