# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]   
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Test with pytest
      id: TestWithPytest
      run: |
           pytest -v --junitxml=report.xml
    - if: ${{failure()}}       
      name: Create Issues
      uses: nashmaniac/create-issue-action@v1.1
      with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: worflow-failed
          body: Workflow failed for commit ${{github.sha}} @ ${{github.ref}}
    
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.5
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: report.xml

  assign:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: add-new-issues-to-repository-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/ETI-Oct2020-Team5/RatVenture/projects/1
        GITHUB_PROJECT_COLUMN_NAME: To do
